name: CustomGUI
version: '${project.version}'
main: customgui.customgui.CustomGUI
api-version: 1.13
authors: [ NeverAfK ]
description: CustomGUIMaker
commands:
  inventory:
    description: Open/Edit/Setup Inventory GUIs or edit Items.
    aliases: gui